#!/usr/bin/env python3
"""
Per-builtin correctness oracle generator.

Parse ingenic-mxu2.def, generate one C wrapper per builtin that:
  - Calls the builtin with deterministic globals (or chosen literals)
  - Prints the output as a stable text format with raw hex bits
  - Composes a single oracle_all.c with one main() that calls every wrapper

The generated source is built with BOTH the GCC15 thingino toolchain and
the Ingenic vendor R5.2.1 toolchain, run on T20 over NFS, and the outputs
diffed line-by-line.

Output: oracle_gen/oracle_all.c
"""
import os
import re
import sys

DEF_FILE = "/home/turismo/projects/mxu-probe/patches/gcc-mxu3-work/mxu2-baseline/gcc/config/mips/ingenic-mxu2.def"
OUT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "oracle_gen")
OUT_C = os.path.join(OUT_DIR, "oracle_all.c")

# Map FTYPE token -> (C type, default arg expression, bit-width-in-bits, kind)
# kind: 'i' integer scalar, 'u' unsigned integer scalar, 'f' float scalar,
#       'd' double scalar, 'vi' integer vector, 'vu' unsigned int vector,
#       'vf' float vector, 'vd' double vector, 'p' pointer, 'imm' immediate
TYPE_MAP = {
    "VOID":      ("void",         None,         0,   "void"),
    "SI":        ("int32_t",      "g_si",       32,  "i"),
    "DI":        ("int64_t",      "g_di",       64,  "i"),
    "USI":       ("uint32_t",     "g_usi",      32,  "u"),
    "UDI":       ("uint64_t",     "g_udi",      64,  "u"),
    # Note: HI in the def file is used for immediates of the li_* builtins.
    # We'll pass a small literal to satisfy the const-int requirement.
    "HI":        ("int16_t",      "0x1234",     16,  "imm"),
    "QI":        ("int8_t",       "g_qi",       8,   "i"),
    "UQI":       ("uint8_t",      "0",          8,   "imm"),
    "UHI":       ("uint16_t",     "0",          16,  "imm"),
    "SF":        ("float",        "g_sf",       32,  "f"),
    "DF":        ("double",       "g_df",       64,  "d"),
    "V16QI":     ("v16i8",        "g_v16qi",    128, "vi"),
    "V8HI":      ("v8i16",        "g_v8hi",     128, "vi"),
    "V4SI":      ("v4i32",        "g_v4si",     128, "vi"),
    "V2DI":      ("v2i64",        "g_v2di",     128, "vi"),
    "V4SF":      ("v4f32",        "g_v4sf",     128, "vf"),
    "V2DF":      ("v2f64",        "g_v2df",     128, "vd"),
    "UV16QI":    ("v16u8",        "g_uv16qi",   128, "vu"),
    "UV8HI":     ("v8u16",        "g_uv8hi",    128, "vu"),
    "UV4SI":     ("v4u32",        "g_uv4si",    128, "vu"),
    "UV2DI":     ("v2u64",        "g_uv2di",    128, "vu"),
    "POINTER":   ("void *",       "g_buf",      0,   "p"),
    "VOIDPTR":   ("void *",       "g_buf",      0,   "p"),
    "CVPOINTER": ("const void *", "g_buf",      0,   "p"),
    "CPOINTER":  ("const void *", "g_buf",      0,   "p"),
}

# These builtins are sensitive to FP rounding mode and may differ even with
# the same hardware. We still generate the test, but mark with FP_DIFF.
FP_TOLERANT = {"fdiv_w", "fdiv_d", "fsqrt_w", "fsqrt_d"}

# Special-case argument lists for builtins where the .def signature doesn't
# convey constraints. Map name -> list-of-arg-source-expressions.
# For lu1q/la1q (and store equivalents): second arg is a constant offset.
# la1q/sa1q need 16-aligned (so use 16, not 0, to exercise) — actually 0 is fine.
SPECIAL_ARGS = {
    # Loads: ptr + const offset
    "lu1q":  ["g_buf", "0"],
    "la1q":  ["g_buf", "0"],
    # x-variants take a register offset, but if we pass g_si the address is
    # wild. Pass a small int local that's known small.
    "lu1qx": ["g_buf", "g_offset"],
    "la1qx": ["g_buf", "g_offset"],
    # Stores: vector + ptr + const offset
    "su1q":  ["g_v16qi", "g_buf", "0"],
    "sa1q":  ["g_v16qi", "g_buf", "0"],
    "su1qx": ["g_v16qi", "g_buf", "g_offset"],
    "sa1qx": ["g_v16qi", "g_buf", "g_offset"],
    # ctcmxu: UQI control reg index (0 is fine), SI value
    "ctcmxu": ["0", "g_si"],
}

# Globals (deterministic). Initialized in main() so the compiler cannot
# constant-fold across translation units. We use designated init values.
GLOBALS = r"""/*
 * Auto-generated by builtin_oracle_gen.py - DO NOT EDIT.
 *
 * Calls every MXU2 builtin parsed from ingenic-mxu2.def, prints raw bits.
 * Output is compared line-by-line between our GCC15 toolchain and vendor
 * R5.2.1 to detect miscompilations.
 */
#include <mxu2.h>
#include <stdio.h>
#include <string.h>
#include <stdint.h>

/* Buffer for pointer-taking builtins (lu1q etc). 64 bytes, 16-aligned. */
static uint8_t g_buf[64] __attribute__((aligned(16))) = {
    0x10,0x11,0x12,0x13,0x14,0x15,0x16,0x17,
    0x18,0x19,0x1a,0x1b,0x1c,0x1d,0x1e,0x1f,
    0x20,0x21,0x22,0x23,0x24,0x25,0x26,0x27,
    0x28,0x29,0x2a,0x2b,0x2c,0x2d,0x2e,0x2f,
    0x30,0x31,0x32,0x33,0x34,0x35,0x36,0x37,
    0x38,0x39,0x3a,0x3b,0x3c,0x3d,0x3e,0x3f,
    0x40,0x41,0x42,0x43,0x44,0x45,0x46,0x47,
    0x48,0x49,0x4a,0x4b,0x4c,0x4d,0x4e,0x4f,
};

/* Scalars. */
static int32_t  g_si  = 0x76543210;
/* Safe small offset for register-based load/store builtins (lu1qx etc).
 * Must be 16-aligned for sa1qx/la1qx. */
static int32_t  g_offset = 16;
static int64_t  g_di  = (int64_t)0xfedcba9876543210LL;
static uint32_t g_usi = 0x12345678u;
static uint64_t g_udi = 0x0123456789abcdefULL;
static int8_t   g_qi  = (int8_t)0xa5;
static int16_t  g_hi  = (int16_t)0x1234;
static float    g_sf;       /* set in main from bits 0x40490fdb (~pi) */
static double   g_df;       /* set in main from bits 0x400921fb54442d18 (~pi) */

/* Vectors. */
static v16i8  g_v16qi = {1,-2,3,-4,5,-6,7,-8,9,-10,11,-12,13,-14,15,-16};
static v8i16  g_v8hi  = {0x0001,0x0002,0x0003,0x0004,
                          0x7ff0,(short)0x8001,0x1234,(short)0xabcd};
static v4i32  g_v4si  = {0x11111111, 0x22222222, 0x33333333, 0x44444444};
static v2i64  g_v2di  = {(long long)0x0123456789abcdefLL,
                          (long long)0xfedcba9876543210LL};
static v4f32  g_v4sf;       /* set in main */
static v2f64  g_v2df;       /* set in main */
static v16u8  g_uv16qi = {0x10,0x20,0x30,0x40,0x50,0x60,0x70,0x80,
                           0x90,0xa0,0xb0,0xc0,0xd0,0xe0,0xf0,0xff};
static v8u16  g_uv8hi  = {0x1001,0x2002,0x3003,0x4004,
                           0x5005,0x6006,0x7007,0x8008};
static v4u32  g_uv4si  = {0x11111111u, 0x22222222u, 0x33333333u, 0x44444444u};
static v2u64  g_uv2di  = {0xdeadbeefcafebabeULL, 0x0123456789abcdefULL};

/* --- helpers for printing raw bits ---------------------------------- */
/* fprintf to stdout with explicit flush so a crash mid-test still leaves
 * a complete line trail on disk, and a malformed stack on entry to
 * wrap_X() doesn't carry garbage into the next wrapper. */
static void p_u32(const char *n, uint32_t v) {
    fprintf(stdout, "%s 0x%08x\n", n, v); fflush(stdout);
}
static void p_u64(const char *n, uint64_t v) {
    fprintf(stdout, "%s 0x%016llx\n", n, (unsigned long long)v); fflush(stdout);
}
static void p_v128(const char *n, const void *vp) {
    const uint32_t *p = (const uint32_t *)vp;
    fprintf(stdout, "%s 0x%08x 0x%08x 0x%08x 0x%08x\n",
            n, p[0], p[1], p[2], p[3]);
    fflush(stdout);
}
static void p_void(const char *n) {
    fprintf(stdout, "%s VOID\n", n); fflush(stdout);
}
static void p_buf(const char *n) {
    /* For VOID-returning builtins that mutate g_buf. */
    const uint32_t *p = (const uint32_t *)g_buf;
    fprintf(stdout, "%s_buf 0x%08x 0x%08x 0x%08x 0x%08x\n",
            n, p[0], p[1], p[2], p[3]);
    fflush(stdout);
}

static union { float f; uint32_t u; } u_sf;
static union { double d; uint64_t u; } u_df;

"""

MAIN_PRELUDE = r"""
int main(void) {
    /* Set FP scalars from raw bits to ensure same value regardless of compiler. */
    u_sf.u = 0x40490fdbu; g_sf = u_sf.f;
    u_df.u = 0x400921fb54442d18ULL; g_df = u_df.d;
    /* Set FP vectors from integer template via memcpy on a u32 buffer. */
    {
        uint32_t sf_bits[4] = {0x40490fdbu, 0xc0490fdbu, 0x3f800000u, 0x40000000u};
        memcpy(&g_v4sf, sf_bits, 16);
    }
    {
        uint64_t df_bits[2] = {0x400921fb54442d18ULL, 0xc00921fb54442d18ULL};
        memcpy(&g_v2df, df_bits, 16);
    }

"""

MAIN_EPILOGUE = """
    return 0;
}
"""


def parse_ftype(ftype):
    """MIPS_V4SI_FTYPE_V4SI_V4SI -> ('V4SI', ['V4SI', 'V4SI'])"""
    m = re.match(r"MIPS_(\w+?)_FTYPE_(.+)", ftype)
    if not m:
        return None
    ret = m.group(1)
    args_part = m.group(2)
    args = []
    rest = args_part
    while rest:
        matched = False
        for key in sorted(TYPE_MAP.keys(), key=lambda k: -len(k)):
            if rest == key or rest.startswith(key + "_"):
                args.append(key)
                rest = rest[len(key):]
                if rest.startswith("_"):
                    rest = rest[1:]
                matched = True
                break
        if not matched:
            return None
    if ret not in TYPE_MAP:
        return None
    return (ret, args)


def gen_wrapper(name, sig):
    """Return (wrapper_function_source, call_in_main_string) or (None, None)
    if we can't represent this builtin yet."""
    ret, args = sig
    if name in SPECIAL_ARGS:
        arg_vals = SPECIAL_ARGS[name]
    else:
        arg_vals = []
        for a in args:
            info = TYPE_MAP.get(a)
            if info is None or info[1] is None:
                return None, None
            arg_vals.append(info[1])
    call = f"__builtin_mxu2_{name}({', '.join(arg_vals)})"

    ret_info = TYPE_MAP[ret]
    ret_kind = ret_info[3]
    body = []
    if ret_kind == "void":
        # Side-effecting builtin; print g_buf state to capture mutation.
        body.append(f"    {call};")
        body.append(f'    p_buf("{name}");')
    elif ret_kind in ("i", "u"):
        # Use 32 or 64 bit print as appropriate.
        if ret_info[2] == 64:
            body.append(f"    uint64_t r = (uint64_t){call};")
            body.append(f'    p_u64("{name}", r);')
        else:
            body.append(f"    uint32_t r = (uint32_t)(int32_t){call};")
            body.append(f'    p_u32("{name}", r);')
    elif ret_kind == "f":
        body.append(f"    union {{ float f; uint32_t u; }} _u; _u.f = {call};")
        body.append(f'    p_u32("{name}", _u.u);')
    elif ret_kind == "d":
        body.append(f"    union {{ double d; uint64_t u; }} _u; _u.d = {call};")
        body.append(f'    p_u64("{name}", _u.u);')
    elif ret_kind in ("vi", "vu", "vf", "vd"):
        body.append(f"    {ret_info[0]} _v = {call};")
        body.append(f'    p_v128("{name}", &_v);')
    else:
        return None, None

    fn_src = (
        f"static __attribute__((noinline)) void wrap_{name}(void) {{\n"
        + "\n".join(body)
        + "\n}\n"
    )
    call_in_main = f"    wrap_{name}();"
    return fn_src, call_in_main


def main():
    builtins = []
    with open(DEF_FILE) as f:
        for line in f:
            m = re.match(
                r"\s*MXU2(?:_NO_TARGET)?_BUILTIN\s*\(\s*(\w+)\s*,\s*(MIPS_[A-Z0-9_]+)\s*\)",
                line,
            )
            if m:
                builtins.append((m.group(1), m.group(2)))
    print(f"parsed {len(builtins)} builtin declarations from {DEF_FILE}")

    os.makedirs(OUT_DIR, exist_ok=True)

    pieces = [GLOBALS]
    main_calls = []
    skipped = []
    fp_diff = []
    emitted = []
    for name, ftype in sorted(builtins):
        sig = parse_ftype(ftype)
        if sig is None:
            skipped.append((name, ftype, "parse"))
            continue
        fn_src, call = gen_wrapper(name, sig)
        if fn_src is None:
            skipped.append((name, ftype, "gen"))
            continue
        pieces.append(fn_src)
        main_calls.append(call)
        emitted.append(name)
        if name in FP_TOLERANT:
            fp_diff.append(name)

    pieces.append(MAIN_PRELUDE)
    pieces.extend(c + "\n" for c in main_calls)
    pieces.append(MAIN_EPILOGUE)

    with open(OUT_C, "w") as f:
        f.write("".join(pieces))

    print(f"wrote {OUT_C}")
    print(f"  emitted wrappers: {len(emitted)}")
    print(f"  skipped: {len(skipped)}")
    if fp_diff:
        # Save list of FP-tolerant builtin names for the driver.
        with open(os.path.join(OUT_DIR, "fp_tolerant.txt"), "w") as f:
            for n in fp_diff:
                f.write(n + "\n")
        print(f"  FP-rounding-sensitive (may differ): {len(fp_diff)}")
    # Save full emitted list for the driver.
    with open(os.path.join(OUT_DIR, "emitted.txt"), "w") as f:
        for n in emitted:
            f.write(n + "\n")
    if skipped:
        with open(os.path.join(OUT_DIR, "skipped.txt"), "w") as f:
            for n, t, why in skipped:
                f.write(f"{n} {t} {why}\n")


if __name__ == "__main__":
    main()
